const app=document.querySelector('#app');let state={};let adminOpen=false;const resource=typeof GetParentResourceName==='function'?GetParentResourceName():'rs-economie';
const money=n=>`${state.config?.currency||'€'}${new Intl.NumberFormat('nl-NL').format(Number(n)||0)}`;
const post=async(name,data={})=>{try{const r=await fetch(`https://${resource}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return await r.json()}catch{return{success:false,message:'Verbinding mislukt.'}}};
const toast=(message,error=false)=>{const el=document.querySelector('#toast');el.textContent=message||'Actie verwerkt.';el.className=`toast show${error?' error':''}`;setTimeout(()=>el.className='toast',2600)};
const setText=(id,text)=>{const el=document.querySelector(`#${id}`);if(el)el.textContent=text};
const titles={overview:'Financieel overzicht',transfer:'Geld overboeken',savings:'Spaarrekening',loans:'Leningen',transactions:'Transacties',admin:'Economisch beheer'};
function page(name){if(name==='admin'&&!state.admin)return;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===name));setText('pageTitle',titles[name])}
function transactionRow(t){const amount=Number(t.amount)||0;const label={transfer_out:'Overschrijving',transfer_in:'Ontvangen',savings_deposit:'Sparen',savings_withdraw:'Opname',loan:'Lening',loan_payment:'Aflossing',admin:'Correctie',interest:'Rente'}[t.type]||t.type;return `<div class="transaction"><div class="transaction-icon">${amount>=0?'↙':'↗'}</div><div><strong>${esc(t.description||label)}</strong><small>${esc(label)} · ${formatDate(t.created_at)}</small></div><span class="transaction-amount ${amount>=0?'positive':'negative'}">${amount>=0?'+':''}${money(amount)}</span></div>`}
function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}function formatDate(v){if(!v)return'Zojuist';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('nl-NL',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function render(){const p=state.player||{};setText('welcomeName',p.name||'Speler');setText('sidebarName',p.name||'Speler');setText('avatar',(p.name||'R')[0].toUpperCase());setText('bankBalance',money(p.bank));setText('cashBalance',money(p.cash));setText('savingsBalance',money(p.savings));setText('savingsBig',money(p.savings));setText('creditScore',p.creditScore||500);setText('transferAvailable',money(p.bank));setText('savingsRate',`Rente ${state.policies?.savings_interest||0}%`);setText('savingsYield',`Je ontvangt ${state.policies?.savings_interest||0}% periodieke rente.`);app.classList.toggle('is-admin',!!state.admin);
 const transactions=state.transactions||[];document.querySelector('#recentTransactions').innerHTML=transactions.slice(0,5).map(transactionRow).join('')||'<div class="empty">Nog geen transacties.</div>';renderTransactions();renderLoans();renderAdmin();const terms=state.config?.loanTerms||[];document.querySelector('#loanTerm').innerHTML=terms.map(x=>`<option value="${x}">${x} dagen</option>`).join('');updateLoanPreview()}
function renderTransactions(){const q=document.querySelector('#transactionSearch').value.toLowerCase();const rows=(state.transactions||[]).filter(t=>`${t.description} ${t.type} ${t.counterparty}`.toLowerCase().includes(q));document.querySelector('#allTransactions').innerHTML=rows.map(transactionRow).join('')||'<div class="empty">Geen transacties gevonden.</div>'}
function renderLoans(){const rows=state.loans||[];document.querySelector('#loanList').innerHTML=rows.map(l=>`<div class="loan"><div class="loan-top"><strong>Lening #${l.id}</strong><strong>${money(l.outstanding)}</strong></div><small>${l.interest_rate}% rente · ${l.term_days} dagen · termijn ${money(l.payment_amount)}</small><button data-pay-loan="${l.id}">Volledig aflossen</button></div>`).join('')||'<div class="empty">Geen actieve leningen.</div>'}
function renderAdmin(){if(!state.admin)return;const s=state.statistics||{};document.querySelector('#adminStats').innerHTML=`<article class="card balance"><span>Totaal spaargeld</span><strong>${money(s.savings)}</strong></article><article class="card balance"><span>Openstaande schuld</span><strong>${money(s.debt)}</strong></article><article class="card balance"><span>Transacties 24u</span><strong>${s.transactions||0}</strong></article><article class="card balance"><span>Volume 24u</span><strong>${money(s.volume)}</strong></article>`;document.querySelector('#auditList').innerHTML=(state.audit||[]).map(a=>`<div class="transaction"><div class="transaction-icon">⚙</div><div><strong>${esc(a.action)}</strong><small>${esc(a.actor_name)} · ${formatDate(a.created_at)}</small></div><span>${a.amount?money(a.amount):''}</span></div>`).join('')||'<div class="empty">Geen beheeracties.</div>'}
function updateLoanPreview(){const amount=Number(document.querySelector('#loanAmount').value)||0;const rate=Number(state.policies?.loan_interest)||0;setText('loanPreview',money(Math.round(amount*(1+rate/100))))}
async function submit(name,form,extra={}){const data=Object.fromEntries(new FormData(form));const result=await post(name,{...data,...extra,admin:adminOpen});toast(result.message,!result.success);if(result.success)form.reset()}
window.addEventListener('message',e=>{if(e.data.action==='open'){adminOpen=!!e.data.admin;app.classList.remove('hidden');page(adminOpen?'admin':'overview')}if(e.data.action==='close')app.classList.add('hidden');if(e.data.action==='hydrate'){state=e.data.payload||{};render()}});
document.querySelector('#close').onclick=()=>post('close');document.addEventListener('keydown',e=>{if(e.key==='Escape')post('close')});document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>page(b.dataset.goto));
document.querySelector('#transferForm').onsubmit=e=>{e.preventDefault();submit('transfer',e.currentTarget)};document.querySelector('#savingsForm').onsubmit=e=>{e.preventDefault();submit('savings',e.currentTarget)};document.querySelector('#loanForm').onsubmit=e=>{e.preventDefault();submit('loan',e.currentTarget)};document.querySelector('#policyForm').onsubmit=e=>{e.preventDefault();submit('updatePolicy',e.currentTarget,{admin:true})};document.querySelector('#adminMutationForm').onsubmit=e=>{e.preventDefault();submit('adminMutation',e.currentTarget,{admin:true})};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#savingsForm [name=direction]').value=b.dataset.direction});document.querySelector('#transactionSearch').oninput=renderTransactions;document.querySelector('#loanAmount').oninput=updateLoanPreview;document.querySelector('#loanList').onclick=async e=>{const id=e.target.dataset.payLoan;if(!id)return;const r=await post('payLoan',{id:Number(id),amount:'all'});toast(r.message,!r.success)};
